export const ENV_CONFIG = {
  // api
  API_URL: process.env.NEXT_PUBLIC_API_URL,

  // lib
  GA_ID: process.env.NEXT_PUBLIC_GA_ID,
  NAVER_MAP_CLIENT_ID: process.env.NEXT_PUBLIC_NAVER_MAP_CLIENT_ID,
  NAVER_MAP_CLIENT_SECRET: process.env.NEXT_PUBLIC_NAVER_MAP_CLIENT_SECRET,
  CHANNEL_TALK_PLUGIN_KEY: process.env.NEXT_PUBLIC_CHANNEL_TALK_PLUGIN_KEY,
};
